export {default as Navbar} from "./Navbar"
export {default as Hero} from "./Hero"
export {default as Footer} from "./Footer"
export {default as Featured} from "./Featured"
export {default as Best} from "./Best"